### ISSUE TITLE
ini_set(): A session is active. You cannot change the session module's ini settings at this time

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-symfony#42]
I'm getting this `PHPUnit\Framework\Exception`:

> ini_set(): A session is active. You cannot change the session module's ini settings at this time

In my `config/packages/test/framework.php`, I have:

```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->extension('framework', [
        'test' => true,
        'csrf_protection' => false,
        'session' => [
            'handler_id' => 'session.handler.native_file',
        ],
    ]);
};
```
https://github.com/Codeception/Codeception/issues/6025 is similar.

When I set the `handler_id` to `null`, this error disappears, but there is another (which I don't know if it's related): https://github.com/Codeception/module-symfony/issues/43

**Comment by delectatech** [comment]
I don't know if it's the cause or not, but if I remove this line: 
`echo "Testing $suiteName\n";`

from this file:

 `/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php` the error disappears.

**Comment by roomm** [comment]
I don't know if it's the cause or not, but if I remove this line:
echo "Testing $suiteName\n";

from this file:

/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php the error disappears.

**Comment by ThomasLandauer** [comment]
Here is this line: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bridge/PhpUnit/Legacy/SymfonyTestsListenerTrait.php#L135

But I don't have this file in my `vendor` directory (`symfony/phpunit-bridge` not in `composer show`), so this can't be the reason in my case.

**Comment by ThomasLandauer** [comment]
After some debugging, I found out:
* The exception gets thrown by Symfony's [`NativeFileSessionHandler::__construct()`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php#L52)
* During my test, this function is called *multiple* times. Doing [`session_status()`](https://www.php.net/manual/function.session-status.php) in there, gives `PHP_SESSION_NONE` first, but `PHP_SESSION_ACTIVE` then.
* The stack trace in Codeception's saved `_output` HTML file shows that the last *Codeception* call is [`Symfony::doRequest()`](https://github.com/Codeception/module-symfony/blob/master/src/Codeception/Lib/Connector/Symfony.php#L64). Then, after around 15 Symfony internal calls, it ultimately ends up at the `NativeFileSessionHandler` (see above).

So the question is: Why is sometimes the previous session not getting closed before trying to start this new one?

**Comment by ThomasLandauer** [comment]
The error is gone now, and I think it was due to this change in `config/packages/test/framework.php`:
```php
'storage_id' => 'session.storage.mock_file',
```
See https://symfony.com/doc/current/reference/configuration/framework.html#storage-id

So I'm closing this.

@TavoNiievez Is it a given fact that Symfony module is only compatible with `session.storage.mock_file`? If yes, we should document this on https://codeception.com/docs/modules/Symfony
(And I'm pretty sure it did work with `session.handler.native_file` too - so this must have changed in the previous months/years.)
