### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, string given

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-symfony#43]
When running the *entire* functional suite, I'm getting this `PHPUnit\Framework\Exception` on many tests:

> array_key_exists() expects parameter 2 to be array, string given

Stack trace is:

2. [Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag::get()](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/Session/Attribute/NamespacedAttributeBag.php#L63)
1. [Symfony\Component\HttpFoundation\Session\Session::get()](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/Session/Session.php#L73)

The odd thing is that this does *not* happen when I run just a single Cest file. It's only when I run the entire suite.

**Comment by TavoNiievez** [comment]
@ThomasLandauer thanks.

Is this related to Symfony Module or is it a Codeception issue when using Symfony classes?

**Comment by ThomasLandauer** [comment]
I'm not sure, how can I find out? I'd rather guess Symfony Module, since Codeception itself probably doesn't use a session.

**Comment by TavoNiievez** [comment]
You can try to reproduce this error in the test project or you can try to disable the symfony module in your other project, if the error persists then it is not related to the module.

**Comment by ThomasLandauer** [comment]
I'm using Symfony's `NamespacedAttributeBag` in my app and made a stupid mistake when fetching the entries. Still don't know why this only occurred when running Codeception ;-) Anyway - I think I fixed it, so I'm closing this.
