### ISSUE TITLE
runSymfonyConsoleCommand with options is not possible

### ISSUE THREAD

**Issue by kes31** [Codeception/module-symfony#46]
It's currently not possible to execute a symfony console command with options given. The reason is, that the class CommandTester expects options given as a second array, this is not supported by the wrapper. The reason is that `runSymfonyConsoleCommand` executes the command with 
`$exitCode = $commandTester->execute($parameters);`
for having working command options a second paramater has to be used:
`$exitCode = $commandTester->execute($parameters, $options);`

**Comment by TavoNiievez** [comment]
@kes31 Thanks for reporting,
However, I was able to pass options to a command with the syntax described in the docblock:
```php
$result = $I->runSymfonyConsoleCommand('hello:world', ['arg' => 'argValue', 'opt1' => 'optValue'], ['input']);
```
In the case of *optional* options, the value you add for the option in the associative array does not matter, it will only take into account the key.
```php
$I->runSymfonyConsoleCommand('app:create-user', ['--admin' => true],
	['John Doe', 'john_doe@github.com', '123456']
);
```
It would make more sense if there was a specific parameter for the options (Or rather, it is not so intuitive that it works like this, but it does).

Note that there are already many parameters in this function, (some questionable like `$expectedOutputCode`), but making those kinds of changes would create unnecessary Breaking Changes.

**Comment by kes31** [comment]
@TavoNiievez Thanks for your respons, I did further analysis on the problem. You can find here a testcase for my original problem where the analysis did not work: https://github.com/kes31/codeception-symfony-options-test.git.
As you can see any value works except `false`.

**Comment by TavoNiievez** [comment]
Maybe [this](https://stackoverflow.com/questions/39406733/how-to-identify-if-an-option-was-supplied-without-a-value-with-symfony-console) will help (?).
