### ISSUE TITLE
Bug with 1.3 seeEmailIsSent() : Failed asserting that 0 is greater than 0.

### ISSUE THREAD

**Issue by TheKassaK** [Codeception/module-symfony#55]
Hi,

When updated the symfony module to 1.3, I have errors when I use function : **seeEmailIsSent()**

I can't use 0 in expected count : **seeEmailIsSent(0)** or use **dontSeeEmailIsSent()**, both throw an error : Failed asserting that 0 is greater than 0.

**Comment by Naktibalda** [comment]
It was caused by https://github.com/Codeception/module-symfony/pull/35

**Comment by TavoNiievez** [comment]
@TheKassaK thanks for reporting, a strict comparison was included to fix it in #56 .

if you update to 1.4.0 everything will work correctly.

**Comment by TheKassaK** [comment]
@TavoNiievez : Thanks you ! I just tried and it’s ok now ;)
