### ISSUE TITLE
The cache_router option breaks routing

### ISSUE THREAD

**Issue by Amunak** [Codeception/module-symfony#8]
Enabling `cache_router` causes a weird issue where the Symfony Matcher (most likely framework-bundle/Routing/Router) has a different instance of `\Symfony\Component\Routing\RequestContext` than the one RouterListener (a HttpKernel Listener responsible for actually calling the Matcher and resolving the route when a Request arrives) has.

RouterListener and Matcher unfortunately require that the RequestContext is the same instance, as RequestListener takes important information from Request (like the HTTP method) and sets it into the Context. Matcher needs to have the correct Context, otherwise it matches the wrong routes.

For instance, when you have a POST request, the Matcher's Context needs to know this so that it matches POST routes and not (the default,) GET routes.

I'm not sure if this is a Codeception bug; it seems like poor architecture on Symfony's part. However it should at least be known and either fixed or there at least needs to be a warning next to the option in documentation. As such I have also opened an issue with Symfony: symfony/symfony#36685.

There is a plain reproducer for Symfony as well if you want to understand the issue better: [Amunak/symfony-routing-bug-reproducer](https://github.com/Amunak/symfony-routing-bug-reproducer). Run it with `php public/index.php` and observe that it returns a GET route instead of a POST route.

**Comment by TavoNiievez** [comment]
@Amunak what is the status of this issue?
It seems that it is actually a symfony problem and is not specific to this module

**Comment by TavoNiievez** [comment]
I am closing this since there is no real problem with the module and if it exists, it is a Symfony problem itself.
