### ISSUE TITLE
How do I mock services in Symfony DIC in functional testing?

### ISSUE THREAD

**Issue by ihorsamusenko** [Codeception/module-symfony#96]
How do I mock services in Symfony DIC in functional testing?

I can do it through some test_services.yml and config_test.yml. But I wonder if there is a better way to be able to mock things directly in tests?

**Comment by TavoNiievez** [comment]
Mocking inside functional tests is unusual, generally, you will want to do a unit or integration test instead, as it tends to be seen [as unnecessary](https://stackoverflow.com/a/61643456).

However, if you really need it...

[The first solution](https://stackoverflow.com/a/19726963) involves mocking the service by disabling the original constructor and then registering the service in the Symfony container dynamically.

[The second solution](https://stackoverflow.com/a/50582734) is to register configuration parameters for the services. Basically, you replace the services to the constructor of your object with the help of the `services_test.yaml` configuration files or [decorate the service](https://stackoverflow.com/a/61726766) using the [factory design pattern](https://symfony.com/doc/current/service_container/factories.html).
