### ISSUE TITLE
Symfony: `.env.local` and `.env.test` are ignored

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-symfony#99]
Starting in November 2018, Symfony has changed the way `.env` files are working: https://symfony.com/doc/current/configuration.html#the-env-file-environment-variables

These changes are not realized in Codeception.

To assert this, I created a controller which just outputs an environment variable:
```php
return new Response(getenv('MAILER_URL'));`
```

When I access the url with codeception (`codecept_debug($I->grabPageSource());`), I always get what I have in `.env` (should be `.env.local` or `.env.test`).

However, when I open the page in the browser in DEV environment, I get the content of `.env.dev`, when in TEST environment, `.env.test`; this is the expected behavior.

### Details

* Codeception version: 2.5.x-dev fc6deb8
* Symfony version: 4.2.1

**Comment by TavoNiievez** [comment]
@ThomasLandauer yeap. Done. Is #88 the same issue?

**Comment by c33s** [comment]
@TavoNiievez via slack:

> can you please check the current status of issue #99?

to sum things up:

codeception should never automatically load any .env files via params (if a user want to load it, they should load it via manual config). the reason behind this is that symfony is loading the dotenv files in a specific way which also differs between symfony versions. to have a correct behavior it should be always loaded like symfony is loading it. https://symfony.com/blog/improvements-to-the-handling-of-env-files-for-all-symfony-versions https://symfony.com/doc/current/configuration/dot-env-changes.html#updating-my-application

for older symfony versions this means we have to include the `bootstrap.php` file where the dotenv loading is done like it's done in https://github.com/Codeception/module-symfony/pull/4

to give a little insignt this is one variant of  `bootstrap.php`
```php
if (is_array($env = @include dirname(__DIR__).'/.env.local.php') && (!isset($env['APP_ENV']) || ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? $env['APP_ENV']) === $env['APP_ENV'])) {
    foreach ($env as $k => $v) {
        $_ENV[$k] = $_ENV[$k] ?? (isset($_SERVER[$k]) && 0 !== strpos($k, 'HTTP_') ? $_SERVER[$k] : $v);
    }
} elseif (!class_exists(Dotenv::class)) {
    throw new RuntimeException('Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.');
} else {
    // load all the .env files
    (new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env');
}
```
but this code also differs between different symfony versions. in older versions the dotenv component was initialized without a parameter, then the parameters was added. in the past the dotenv code was inside of the `console` and `index.php` then it moved into the dotenv component.

so the code in https://github.com/Codeception/module-symfony/pull/4 should be adapted to handle this.

**Comment by gravitiq-cm** [comment]
Is there any update on this? Just started trying to use codeception and got stung by this unexpected dotenv behaviour - wasted a few hours trying to figure it out, which almost put me off using codeception altogether...

**Comment by Naktibalda** [comment]
No updates. I haven't used this module since I posted my comment 3 years ago.

**Comment by TavoNiievez** [comment]
No updates from my side either.

**Comment by TavoNiievez** [comment]
For anyone interested, especially @ThomasLandauer and @c33s I opened a new PR for this: #190
